
-- ----------------------------
-- Table structure for JASDOC_APPLY_FILE_REF
-- ----------------------------
DROP TABLE IF EXISTS "JASDOC_APPLY_FILE_REF";
CREATE TABLE "JASDOC_APPLY_FILE_REF" (
"EVENTID" VARCHAR2(38 BYTE) NOT NULL ,
"APPLYEVENTID" VARCHAR2(38 BYTE) NULL ,
"FILEEVENTID" VARCHAR2(38 BYTE) NULL ,
"FILETYPE" NUMBER NULL 
)
LOGGING
NOCOMPRESS
NOCACHE

;
COMMENT ON TABLE "JASDOC_APPLY_FILE_REF" IS '下载申请-文档关联表';
COMMENT ON COLUMN "JASDOC_APPLY_FILE_REF"."EVENTID" IS 'uuid';
COMMENT ON COLUMN "JASDOC_APPLY_FILE_REF"."APPLYEVENTID" IS '申请id';
COMMENT ON COLUMN "JASDOC_APPLY_FILE_REF"."FILEEVENTID" IS '文件或文件夹id';
COMMENT ON COLUMN "JASDOC_APPLY_FILE_REF"."FILETYPE" IS '类型，0表示文件，1表示文件夹';

-- ----------------------------
-- Table structure for JASDOC_CLASSIFY_FOLDER
-- ----------------------------
DROP TABLE IF EXISTS "JASDOC_CLASSIFY_FOLDER";
CREATE TABLE "JASDOC_CLASSIFY_FOLDER" (
"ID" VARCHAR2(36 BYTE) NOT NULL ,
"PARENTID" VARCHAR2(36 BYTE) NOT NULL ,
"FOLDERNAME" VARCHAR2(200 BYTE) NOT NULL ,
"FOLDERLOCATION" VARCHAR2(500 BYTE) NULL ,
"CREATETIME" DATE NULL ,
"CREATEUSER" VARCHAR2(36 BYTE) NULL ,
"SORT" NUMBER(38) DEFAULT 1  NULL ,
"HIERARCHY" VARCHAR2(208 BYTE) NULL ,
"DELETEFLAG" VARCHAR2(36 BYTE) DEFAULT 0  NULL ,
"DELETEUSER" VARCHAR2(36 BYTE) NULL ,
"UPDATEUSER" VARCHAR2(36 BYTE) NULL ,
"UPDATETIME" DATE NULL ,
"EXT_FIELD1" VARCHAR2(500 BYTE) NULL ,
"EXT_FIELD2" VARCHAR2(500 BYTE) NULL ,
"EXT_FIELD3" VARCHAR2(500 BYTE) NULL ,
"EXT_FIELD4" VARCHAR2(500 BYTE) NULL ,
"EXT_FIELD5" VARCHAR2(500 BYTE) NULL ,
"DESCRIPTION" VARCHAR2(1000 BYTE) NULL 
)
LOGGING
NOCOMPRESS
NOCACHE

;
COMMENT ON TABLE "JASDOC_CLASSIFY_FOLDER" IS '文档分类信息，文件夹的层次编号在所有文件夹中是唯一的，包括已放入回收站的文件夹。';
COMMENT ON COLUMN "JASDOC_CLASSIFY_FOLDER"."ID" IS '节点id';
COMMENT ON COLUMN "JASDOC_CLASSIFY_FOLDER"."PARENTID" IS '父类id';
COMMENT ON COLUMN "JASDOC_CLASSIFY_FOLDER"."FOLDERNAME" IS '节点名称';
COMMENT ON COLUMN "JASDOC_CLASSIFY_FOLDER"."CREATETIME" IS '创建时间';
COMMENT ON COLUMN "JASDOC_CLASSIFY_FOLDER"."CREATEUSER" IS '添加数据用户';
COMMENT ON COLUMN "JASDOC_CLASSIFY_FOLDER"."DELETEFLAG" IS '删除标识';
COMMENT ON COLUMN "JASDOC_CLASSIFY_FOLDER"."DELETEUSER" IS '删除该条数据用户id（没有删除则为空）';
COMMENT ON COLUMN "JASDOC_CLASSIFY_FOLDER"."UPDATEUSER" IS '修改数据用户';
COMMENT ON COLUMN "JASDOC_CLASSIFY_FOLDER"."UPDATETIME" IS '创建时间';
COMMENT ON COLUMN "JASDOC_CLASSIFY_FOLDER"."EXT_FIELD1" IS '备用字段';
COMMENT ON COLUMN "JASDOC_CLASSIFY_FOLDER"."EXT_FIELD2" IS '备用字段';
COMMENT ON COLUMN "JASDOC_CLASSIFY_FOLDER"."EXT_FIELD3" IS '备用字段';
COMMENT ON COLUMN "JASDOC_CLASSIFY_FOLDER"."EXT_FIELD4" IS '备用字段';
COMMENT ON COLUMN "JASDOC_CLASSIFY_FOLDER"."EXT_FIELD5" IS '备用字段';
COMMENT ON COLUMN "JASDOC_CLASSIFY_FOLDER"."DESCRIPTION" IS '文件夹描述';

-- ----------------------------
-- Table structure for JASDOC_DELETEINDEX
-- ----------------------------
DROP TABLE IF EXISTS "JASDOC_DELETEINDEX";
CREATE TABLE "JASDOC_DELETEINDEX" (
"DOCEVENTID" NVARCHAR2(38) NULL 
)
LOGGING
NOCOMPRESS
NOCACHE

;

-- ----------------------------
-- Table structure for JASDOC_DEPT_FOLDER_REF
-- ----------------------------
DROP TABLE IF EXISTS "JASDOC_DEPT_FOLDER_REF";
CREATE TABLE "JASDOC_DEPT_FOLDER_REF" (
"ID" VARCHAR2(36 BYTE) NOT NULL ,
"DEPTID" VARCHAR2(36 BYTE) NULL ,
"FOLDERID" VARCHAR2(36 BYTE) NULL ,
"FOLDERPRIVILEGETYPE" NUMBER(3) NULL 
)
LOGGING
NOCOMPRESS
NOCACHE

;
COMMENT ON TABLE "JASDOC_DEPT_FOLDER_REF" IS '部门对文件夹授权';
COMMENT ON COLUMN "JASDOC_DEPT_FOLDER_REF"."ID" IS 'uuid';
COMMENT ON COLUMN "JASDOC_DEPT_FOLDER_REF"."DEPTID" IS '部门id';
COMMENT ON COLUMN "JASDOC_DEPT_FOLDER_REF"."FOLDERID" IS '资源树节点id';

-- ----------------------------
-- Table structure for JASDOC_DOWNLOAD_APPLY
-- ----------------------------
DROP TABLE IF EXISTS "JASDOC_DOWNLOAD_APPLY";
CREATE TABLE "JASDOC_DOWNLOAD_APPLY" (
"EVENTID" VARCHAR2(38 BYTE) NOT NULL ,
"CREATEUSER" VARCHAR2(38 BYTE) NULL ,
"CREATEDATE" DATE NULL ,
"REASON" VARCHAR2(500 BYTE) NULL ,
"APPROVESTATUS" NUMBER NULL ,
"REMARK" VARCHAR2(500 BYTE) NULL ,
"TITLE" VARCHAR2(100 BYTE) NULL ,
"CREATEUSERNAME" VARCHAR2(50 BYTE) NULL ,
"UPDATEDATE" DATE NULL 
)
LOGGING
NOCOMPRESS
NOCACHE

;
COMMENT ON TABLE "JASDOC_DOWNLOAD_APPLY" IS '文档下载申请表';
COMMENT ON COLUMN "JASDOC_DOWNLOAD_APPLY"."EVENTID" IS 'uuid';
COMMENT ON COLUMN "JASDOC_DOWNLOAD_APPLY"."CREATEUSER" IS '申请人';
COMMENT ON COLUMN "JASDOC_DOWNLOAD_APPLY"."CREATEDATE" IS '申请时间';
COMMENT ON COLUMN "JASDOC_DOWNLOAD_APPLY"."REASON" IS '申请理由';
COMMENT ON COLUMN "JASDOC_DOWNLOAD_APPLY"."APPROVESTATUS" IS '审核状态';
COMMENT ON COLUMN "JASDOC_DOWNLOAD_APPLY"."REMARK" IS '备注';
COMMENT ON COLUMN "JASDOC_DOWNLOAD_APPLY"."TITLE" IS '标题';
COMMENT ON COLUMN "JASDOC_DOWNLOAD_APPLY"."CREATEUSERNAME" IS '申请人姓名';
COMMENT ON COLUMN "JASDOC_DOWNLOAD_APPLY"."UPDATEDATE" IS '修改日期';

-- ----------------------------
-- Table structure for JASDOC_FAVORITE_FOLDER
-- ----------------------------
DROP TABLE IF EXISTS "JASDOC_FAVORITE_FOLDER";
CREATE TABLE "JASDOC_FAVORITE_FOLDER" (
"ID" VARCHAR2(36 BYTE) NOT NULL ,
"PARENTID" VARCHAR2(36 BYTE) NOT NULL ,
"FOLDERNAME" VARCHAR2(200 BYTE) NOT NULL ,
"FOLDERLOCATION" VARCHAR2(500 BYTE) NULL ,
"CREATETIME" DATE NULL ,
"CREATEUSER" VARCHAR2(36 BYTE) NULL ,
"SORT" NUMBER(38) NULL ,
"HIERARCHY" VARCHAR2(208 BYTE) NULL ,
"DELETEFLAG" VARCHAR2(36 BYTE) DEFAULT 0  NULL ,
"DELETEUSER" VARCHAR2(36 BYTE) NULL ,
"UPDATEUSER" VARCHAR2(36 BYTE) NULL ,
"UPDATETIME" DATE NULL ,
"EXT_FIELD1" VARCHAR2(500 BYTE) NULL ,
"EXT_FIELD2" VARCHAR2(500 BYTE) NULL ,
"EXT_FIELD3" VARCHAR2(500 BYTE) NULL ,
"EXT_FIELD4" VARCHAR2(500 BYTE) NULL ,
"EXT_FIELD5" VARCHAR2(500 BYTE) NULL ,
"DESCRIPTION" VARCHAR2(1000 BYTE) NULL 
)
LOGGING
NOCOMPRESS
NOCACHE

;
COMMENT ON TABLE "JASDOC_FAVORITE_FOLDER" IS '我的收藏夹表信息，文件夹的层次编号在所有文件夹中是唯一的，包括已放入回收站的文件夹。';
COMMENT ON COLUMN "JASDOC_FAVORITE_FOLDER"."ID" IS '节点id';
COMMENT ON COLUMN "JASDOC_FAVORITE_FOLDER"."PARENTID" IS '父类id';
COMMENT ON COLUMN "JASDOC_FAVORITE_FOLDER"."FOLDERNAME" IS '节点名称';
COMMENT ON COLUMN "JASDOC_FAVORITE_FOLDER"."CREATETIME" IS '创建时间';
COMMENT ON COLUMN "JASDOC_FAVORITE_FOLDER"."CREATEUSER" IS '添加数据用户';
COMMENT ON COLUMN "JASDOC_FAVORITE_FOLDER"."DELETEFLAG" IS '删除标识';
COMMENT ON COLUMN "JASDOC_FAVORITE_FOLDER"."DELETEUSER" IS '删除该条数据用户id（没有删除则为空）';
COMMENT ON COLUMN "JASDOC_FAVORITE_FOLDER"."UPDATEUSER" IS '修改数据用户';
COMMENT ON COLUMN "JASDOC_FAVORITE_FOLDER"."UPDATETIME" IS '创建时间';
COMMENT ON COLUMN "JASDOC_FAVORITE_FOLDER"."EXT_FIELD1" IS '备用字段';
COMMENT ON COLUMN "JASDOC_FAVORITE_FOLDER"."EXT_FIELD2" IS '备用字段';
COMMENT ON COLUMN "JASDOC_FAVORITE_FOLDER"."EXT_FIELD3" IS '备用字段';
COMMENT ON COLUMN "JASDOC_FAVORITE_FOLDER"."EXT_FIELD4" IS '备用字段';
COMMENT ON COLUMN "JASDOC_FAVORITE_FOLDER"."EXT_FIELD5" IS '备用字段';
COMMENT ON COLUMN "JASDOC_FAVORITE_FOLDER"."DESCRIPTION" IS '文件夹描述';

-- ----------------------------
-- Table structure for JASDOC_FILE
-- ----------------------------
DROP TABLE IF EXISTS "JASDOC_FILE";
CREATE TABLE "JASDOC_FILE" (
"EVENTID" VARCHAR2(38 BYTE) NOT NULL ,
"FOLDERID" VARCHAR2(38 BYTE) NULL ,
"FILENO" VARCHAR2(50 BYTE) NULL ,
"FILENAME" VARCHAR2(200 BYTE) NULL ,
"FILETYPE" VARCHAR2(50 BYTE) NULL ,
"FILELOCATION" VARCHAR2(500 BYTE) NULL ,
"AUTHOR" VARCHAR2(50 BYTE) NULL ,
"KEYWORD" VARCHAR2(50 BYTE) NULL ,
"SUMMARY" VARCHAR2(4000 BYTE) NULL ,
"FILEOBJ" BLOB NULL ,
"FILESIZE" NUMBER NULL ,
"UPLOADTIME" DATE NULL ,
"CREATEUSER" VARCHAR2(50 BYTE) NULL ,
"CREATETIME" DATE NULL ,
"UPDATEUSER" VARCHAR2(50 BYTE) NULL ,
"UPDATETIME" DATE NULL ,
"REMARK" VARCHAR2(4000 BYTE) NULL ,
"DELETEFLAG" VARCHAR2(50 BYTE) DEFAULT 0  NOT NULL ,
"ABSOLUTEPATH" VARCHAR2(500 BYTE) NULL ,
"DELETEUSER" VARCHAR2(50 BYTE) NULL ,
"ISCREATEINDEX" NUMBER(1) DEFAULT 0  NULL ,
"CREATEUSERNAME" NVARCHAR2(50) NULL ,
"VERSIONNUMBER" VARCHAR2(10 BYTE) NULL ,
"VERSIONID" VARCHAR2(38 BYTE) NULL ,
"VERSIONREARK" VARCHAR2(300 BYTE) NULL ,
"VERSIONUPDATETIME" DATE NULL ,
"AUDITSTATE" NUMBER(1) DEFAULT 0  NULL ,
"AUDITUSER" VARCHAR2(50 BYTE) NULL ,
"AUDITTIME" DATE NULL ,
"EXT_FIELD1" VARCHAR2(500 BYTE) NULL ,
"EXT_FIELD2" VARCHAR2(500 BYTE) NULL ,
"EXT_FIELD3" VARCHAR2(500 BYTE) NULL ,
"EXT_FIELD4" VARCHAR2(500 BYTE) NULL ,
"EXT_FIELD5" VARCHAR2(500 BYTE) NULL ,
"DESCRIPTION" VARCHAR2(500 BYTE) NULL ,
"ISPREVIEWCONVERSION" NUMBER(1) DEFAULT 0  NULL ,
"ISADDWATERMARK" NUMBER(1) DEFAULT 0  NULL ,
"UPDATEUSERNAME" NVARCHAR2(50) NULL 
)
LOGGING
NOCOMPRESS
NOCACHE

;
COMMENT ON TABLE "JASDOC_FILE" IS '文档信息';
COMMENT ON COLUMN "JASDOC_FILE"."EVENTID" IS 'uuid';
COMMENT ON COLUMN "JASDOC_FILE"."FILENO" IS '编号';
COMMENT ON COLUMN "JASDOC_FILE"."FILENAME" IS '文件名';
COMMENT ON COLUMN "JASDOC_FILE"."FILETYPE" IS '文档的格如doc、xls。';
COMMENT ON COLUMN "JASDOC_FILE"."FILELOCATION" IS '文档存储在的文件夹';
COMMENT ON COLUMN "JASDOC_FILE"."AUTHOR" IS '创建者';
COMMENT ON COLUMN "JASDOC_FILE"."KEYWORD" IS '关键词';
COMMENT ON COLUMN "JASDOC_FILE"."SUMMARY" IS '摘要';
COMMENT ON COLUMN "JASDOC_FILE"."FILEOBJ" IS '文件本身';
COMMENT ON COLUMN "JASDOC_FILE"."FILESIZE" IS '文件的大小';
COMMENT ON COLUMN "JASDOC_FILE"."UPLOADTIME" IS '附件上传时间';
COMMENT ON COLUMN "JASDOC_FILE"."CREATEUSER" IS '创建者';
COMMENT ON COLUMN "JASDOC_FILE"."CREATETIME" IS '建档时间';
COMMENT ON COLUMN "JASDOC_FILE"."UPDATEUSER" IS '创建者';
COMMENT ON COLUMN "JASDOC_FILE"."UPDATETIME" IS '最近一次修改的时间';
COMMENT ON COLUMN "JASDOC_FILE"."REMARK" IS '备注';
COMMENT ON COLUMN "JASDOC_FILE"."DELETEFLAG" IS '文档删除标识（被删除后该字段为删除批次）(修改字段)';
COMMENT ON COLUMN "JASDOC_FILE"."ABSOLUTEPATH" IS '文件存储在服务器的相对路径，相对应用程序的根目录';
COMMENT ON COLUMN "JASDOC_FILE"."DELETEUSER" IS '删除者';
COMMENT ON COLUMN "JASDOC_FILE"."ISCREATEINDEX" IS '是否添加索引';
COMMENT ON COLUMN "JASDOC_FILE"."CREATEUSERNAME" IS '创建者';
COMMENT ON COLUMN "JASDOC_FILE"."VERSIONNUMBER" IS '版本号';
COMMENT ON COLUMN "JASDOC_FILE"."VERSIONID" IS '历史版本ID';
COMMENT ON COLUMN "JASDOC_FILE"."VERSIONREARK" IS '版本描述';
COMMENT ON COLUMN "JASDOC_FILE"."VERSIONUPDATETIME" IS '版本更新时间';
COMMENT ON COLUMN "JASDOC_FILE"."AUDITSTATE" IS '审核状态';
COMMENT ON COLUMN "JASDOC_FILE"."AUDITUSER" IS '审核人';
COMMENT ON COLUMN "JASDOC_FILE"."AUDITTIME" IS '审核时间';
COMMENT ON COLUMN "JASDOC_FILE"."EXT_FIELD1" IS '备用字段';
COMMENT ON COLUMN "JASDOC_FILE"."EXT_FIELD2" IS '备用字段';
COMMENT ON COLUMN "JASDOC_FILE"."EXT_FIELD3" IS '备用字段';
COMMENT ON COLUMN "JASDOC_FILE"."EXT_FIELD4" IS '备用字段';
COMMENT ON COLUMN "JASDOC_FILE"."EXT_FIELD5" IS '备用字段';
COMMENT ON COLUMN "JASDOC_FILE"."DESCRIPTION" IS '描述信息';
COMMENT ON COLUMN "JASDOC_FILE"."ISPREVIEWCONVERSION" IS '是否已经进行预览转换';
COMMENT ON COLUMN "JASDOC_FILE"."ISADDWATERMARK" IS '是否已经添加水印';
COMMENT ON COLUMN "JASDOC_FILE"."UPDATEUSERNAME" IS '修改者名称';

-- ----------------------------
-- Table structure for JASDOC_FILE_ASSOCIATED
-- ----------------------------
DROP TABLE IF EXISTS "JASDOC_FILE_ASSOCIATED";
CREATE TABLE "JASDOC_FILE_ASSOCIATED" (
"EVENTID" VARCHAR2(38 BYTE) NOT NULL ,
"FILEID" VARCHAR2(38 BYTE) NOT NULL ,
"DESCRIPTION" VARCHAR2(2000 BYTE) NULL ,
"ASSOCIATEDDATE" DATE NULL ,
"ASSOCIATEDUSERID" VARCHAR2(38 BYTE) NULL ,
"ASSOCIATEDPRIVILEGETYPE" NUMBER(3) NULL ,
"ASSOCIATEDFILEID" VARCHAR2(38 BYTE) NULL 
)
LOGGING
NOCOMPRESS
NOCACHE

;
COMMENT ON TABLE "JASDOC_FILE_ASSOCIATED" IS '关联文档';
COMMENT ON COLUMN "JASDOC_FILE_ASSOCIATED"."EVENTID" IS 'uuid';
COMMENT ON COLUMN "JASDOC_FILE_ASSOCIATED"."FILEID" IS '文件id';
COMMENT ON COLUMN "JASDOC_FILE_ASSOCIATED"."DESCRIPTION" IS '描述';
COMMENT ON COLUMN "JASDOC_FILE_ASSOCIATED"."ASSOCIATEDDATE" IS '关联日期';
COMMENT ON COLUMN "JASDOC_FILE_ASSOCIATED"."ASSOCIATEDUSERID" IS '关联人id';

-- ----------------------------
-- Table structure for JASDOC_FILE_BACKUP_RECOVERY
-- ----------------------------
DROP TABLE IF EXISTS "JASDOC_FILE_BACKUP_RECOVERY";
CREATE TABLE "JASDOC_FILE_BACKUP_RECOVERY" (
"EVENTID" VARCHAR2(38 BYTE) NOT NULL ,
"FILEDESCRIPTION" VARCHAR2(2000 BYTE) NULL ,
"CREATEDBY" VARCHAR2(100 BYTE) NULL ,
"CREATEDDATE" DATE NULL ,
"REMARKS" VARCHAR2(2000 BYTE) NULL ,
"BACKUPDATABASEPATH" VARCHAR2(200 BYTE) NULL ,
"BACKUPFILEPATH" VARCHAR2(200 BYTE) NULL ,
"BACKUPINDEXPATH" VARCHAR2(200 BYTE) NULL ,
"BACKUPTASKDATE" DATE NULL ,
"ISOPENBACKUPFUNCTION" NUMBER(1) NULL ,
"EXECUTIONFREQUENCY" NUMBER(2) NULL 
)
LOGGING
NOCOMPRESS
NOCACHE

;
COMMENT ON COLUMN "JASDOC_FILE_BACKUP_RECOVERY"."EVENTID" IS 'uuid';
COMMENT ON COLUMN "JASDOC_FILE_BACKUP_RECOVERY"."FILEDESCRIPTION" IS '描述';
COMMENT ON COLUMN "JASDOC_FILE_BACKUP_RECOVERY"."CREATEDBY" IS '创建人';
COMMENT ON COLUMN "JASDOC_FILE_BACKUP_RECOVERY"."CREATEDDATE" IS '创建时间';
COMMENT ON COLUMN "JASDOC_FILE_BACKUP_RECOVERY"."BACKUPDATABASEPATH" IS '备份路径';
COMMENT ON COLUMN "JASDOC_FILE_BACKUP_RECOVERY"."BACKUPFILEPATH" IS '文件路径';

-- ----------------------------
-- Table structure for JASDOC_FILE_CLASSIFY_REF
-- ----------------------------
DROP TABLE IF EXISTS "JASDOC_FILE_CLASSIFY_REF";
CREATE TABLE "JASDOC_FILE_CLASSIFY_REF" (
"FILEID" VARCHAR2(41 BYTE) NOT NULL ,
"FOLDERID" VARCHAR2(36 BYTE) NOT NULL ,
"EVENTID" VARCHAR2(38 BYTE) NOT NULL 
)
LOGGING
NOCOMPRESS
NOCACHE

;
COMMENT ON TABLE "JASDOC_FILE_CLASSIFY_REF" IS '文档与文档分类关联信息';
COMMENT ON COLUMN "JASDOC_FILE_CLASSIFY_REF"."FILEID" IS '文件id';
COMMENT ON COLUMN "JASDOC_FILE_CLASSIFY_REF"."FOLDERID" IS '父类id';
COMMENT ON COLUMN "JASDOC_FILE_CLASSIFY_REF"."EVENTID" IS '主键id';

-- ----------------------------
-- Table structure for JASDOC_FILE_FAVORITE_REF
-- ----------------------------
DROP TABLE IF EXISTS "JASDOC_FILE_FAVORITE_REF";
CREATE TABLE "JASDOC_FILE_FAVORITE_REF" (
"FILEID" VARCHAR2(41 BYTE) NOT NULL ,
"FOLDERID" VARCHAR2(36 BYTE) NOT NULL ,
"EVENTID" VARCHAR2(38 BYTE) NOT NULL ,
"FILENAME" VARCHAR2(41 CHAR) NOT NULL 
)
LOGGING
NOCOMPRESS
NOCACHE

;
COMMENT ON TABLE "JASDOC_FILE_FAVORITE_REF" IS '文档与收藏夹关联信息；';
COMMENT ON COLUMN "JASDOC_FILE_FAVORITE_REF"."FILEID" IS '文件id';
COMMENT ON COLUMN "JASDOC_FILE_FAVORITE_REF"."FOLDERID" IS '父类id';
COMMENT ON COLUMN "JASDOC_FILE_FAVORITE_REF"."EVENTID" IS '主键id';
COMMENT ON COLUMN "JASDOC_FILE_FAVORITE_REF"."FILENAME" IS '节点名称';

-- ----------------------------
-- Table structure for JASDOC_FILE_FOLDER_REF
-- ----------------------------
DROP TABLE IF EXISTS "JASDOC_FILE_FOLDER_REF";
CREATE TABLE "JASDOC_FILE_FOLDER_REF" (
"FILEID" VARCHAR2(41 BYTE) NOT NULL ,
"FOLDERID" VARCHAR2(36 BYTE) NOT NULL 
)
LOGGING
NOCOMPRESS
NOCACHE

;
COMMENT ON TABLE "JASDOC_FILE_FOLDER_REF" IS '1.文档与文档分类关联信息； 2.文档与我的收藏夹关联信息。';
COMMENT ON COLUMN "JASDOC_FILE_FOLDER_REF"."FOLDERID" IS '节点id';

-- ----------------------------
-- Table structure for JASDOC_FILE_HISTORY
-- ----------------------------
DROP TABLE IF EXISTS "JASDOC_FILE_HISTORY";
CREATE TABLE "JASDOC_FILE_HISTORY" (
"SID" NUMBER(27) NULL ,
"EVENTID" VARCHAR2(36 BYTE) NOT NULL ,
"FOLDERID" VARCHAR2(36 BYTE) NULL ,
"FILENO" VARCHAR2(50 BYTE) NULL ,
"FILENAME" VARCHAR2(80 BYTE) NULL ,
"FILETYPE" VARCHAR2(20 BYTE) NULL ,
"FILELOCATION" VARCHAR2(500 BYTE) NULL ,
"AUTHOR" VARCHAR2(50 BYTE) NULL ,
"KEYWORD" VARCHAR2(50 BYTE) NULL ,
"SUMMARY" VARCHAR2(4000 BYTE) NULL ,
"FILEOBJ" BLOB NULL ,
"FILESIZE" NUMBER NULL ,
"UPLOADTIME" DATE NULL ,
"CREATEUSER" VARCHAR2(50 BYTE) NULL ,
"CREATETIME" DATE NULL ,
"UPDATEUSER" VARCHAR2(50 BYTE) NULL ,
"UPDATETIME" DATE NULL ,
"REMARK" VARCHAR2(4000 BYTE) NULL ,
"DELETEFLAG" VARCHAR2(50 BYTE) DEFAULT 0  NOT NULL ,
"ABSOLUTEPATH" VARCHAR2(300 BYTE) NULL ,
"DELETEUSER" VARCHAR2(50 BYTE) NULL ,
"ISCREATEINDEX" NUMBER(1) DEFAULT 0  NULL ,
"CREATEUSERNAME" VARCHAR2(50 BYTE) NULL ,
"VERSIONNUMBER" VARCHAR2(10 BYTE) NULL ,
"VERSIONID" VARCHAR2(36 BYTE) NOT NULL ,
"VERSIONREARK" VARCHAR2(300 BYTE) NULL ,
"VERSIONUPDATETIME" DATE NULL 
)
LOGGING
NOCOMPRESS
NOCACHE

;
COMMENT ON TABLE "JASDOC_FILE_HISTORY" IS '文档历史';
COMMENT ON COLUMN "JASDOC_FILE_HISTORY"."EVENTID" IS 'uuid';
COMMENT ON COLUMN "JASDOC_FILE_HISTORY"."FILENO" IS '编号';
COMMENT ON COLUMN "JASDOC_FILE_HISTORY"."FILENAME" IS '文件名';
COMMENT ON COLUMN "JASDOC_FILE_HISTORY"."FILETYPE" IS '文档的格式???如doc、xls。';
COMMENT ON COLUMN "JASDOC_FILE_HISTORY"."FILELOCATION" IS '文件的相对父节点位置';
COMMENT ON COLUMN "JASDOC_FILE_HISTORY"."AUTHOR" IS '创建者';
COMMENT ON COLUMN "JASDOC_FILE_HISTORY"."KEYWORD" IS '关键词';
COMMENT ON COLUMN "JASDOC_FILE_HISTORY"."SUMMARY" IS '摘要';
COMMENT ON COLUMN "JASDOC_FILE_HISTORY"."FILEOBJ" IS '文件本身';
COMMENT ON COLUMN "JASDOC_FILE_HISTORY"."FILESIZE" IS '文件的大小';
COMMENT ON COLUMN "JASDOC_FILE_HISTORY"."UPLOADTIME" IS '附件上传时间';
COMMENT ON COLUMN "JASDOC_FILE_HISTORY"."CREATEUSER" IS '创建者';
COMMENT ON COLUMN "JASDOC_FILE_HISTORY"."CREATETIME" IS '建档时间';
COMMENT ON COLUMN "JASDOC_FILE_HISTORY"."UPDATEUSER" IS '创建者';
COMMENT ON COLUMN "JASDOC_FILE_HISTORY"."UPDATETIME" IS '最近一次修改的时间';
COMMENT ON COLUMN "JASDOC_FILE_HISTORY"."REMARK" IS '备注';
COMMENT ON COLUMN "JASDOC_FILE_HISTORY"."DELETEFLAG" IS '文档删除标识（被删除后该字段为删除批次）(修改字段)';
COMMENT ON COLUMN "JASDOC_FILE_HISTORY"."ABSOLUTEPATH" IS '文件的存储绝对路径（新加字段）';
COMMENT ON COLUMN "JASDOC_FILE_HISTORY"."DELETEUSER" IS '删除记录人（新加字段）';
COMMENT ON COLUMN "JASDOC_FILE_HISTORY"."ISCREATEINDEX" IS '是否添加索引';
COMMENT ON COLUMN "JASDOC_FILE_HISTORY"."CREATEUSERNAME" IS '上传用户名称';
COMMENT ON COLUMN "JASDOC_FILE_HISTORY"."VERSIONNUMBER" IS '版本号';
COMMENT ON COLUMN "JASDOC_FILE_HISTORY"."VERSIONID" IS '历史版本id';
COMMENT ON COLUMN "JASDOC_FILE_HISTORY"."VERSIONREARK" IS '版本描述';
COMMENT ON COLUMN "JASDOC_FILE_HISTORY"."VERSIONUPDATETIME" IS '版本更新时间';

-- ----------------------------
-- Table structure for JASDOC_FILE_SHARE
-- ----------------------------
DROP TABLE IF EXISTS "JASDOC_FILE_SHARE";
CREATE TABLE "JASDOC_FILE_SHARE" (
"ID" VARCHAR2(36 BYTE) NOT NULL ,
"FILEID" VARCHAR2(36 BYTE) NULL ,
"SHAREUSERID" VARCHAR2(36 BYTE) NULL ,
"REMARK" VARCHAR2(500 BYTE) NULL ,
"SHAREDATE" DATE NULL ,
"OVERDATE" DATE NULL ,
"SHAREPRIVILEGETYPE" NUMBER(3) NULL 
)
LOGGING
NOCOMPRESS
NOCACHE

;
COMMENT ON TABLE "JASDOC_FILE_SHARE" IS '文档共享';
COMMENT ON COLUMN "JASDOC_FILE_SHARE"."FILEID" IS '文档ID';
COMMENT ON COLUMN "JASDOC_FILE_SHARE"."SHAREUSERID" IS '共享人ID';
COMMENT ON COLUMN "JASDOC_FILE_SHARE"."REMARK" IS '共享说明';
COMMENT ON COLUMN "JASDOC_FILE_SHARE"."SHAREDATE" IS '共享时间';
COMMENT ON COLUMN "JASDOC_FILE_SHARE"."OVERDATE" IS '共享过期时间';
COMMENT ON COLUMN "JASDOC_FILE_SHARE"."SHAREPRIVILEGETYPE" IS '共享权限类型';

-- ----------------------------
-- Table structure for JASDOC_FILE_SHARE_USER_REF
-- ----------------------------
DROP TABLE IF EXISTS "JASDOC_FILE_SHARE_USER_REF";
CREATE TABLE "JASDOC_FILE_SHARE_USER_REF" (
"ID" VARCHAR2(36 BYTE) NOT NULL ,
"JASDOC_FILE_SHEAR_ID" VARCHAR2(36 BYTE) NULL ,
"SHAREDID" VARCHAR2(36 BYTE) NULL ,
"SHAREDTYPE" NUMBER(3) NULL 
)
LOGGING
NOCOMPRESS
NOCACHE

;
COMMENT ON TABLE "JASDOC_FILE_SHARE_USER_REF" IS '共享文档与用户关联表';
COMMENT ON COLUMN "JASDOC_FILE_SHARE_USER_REF"."JASDOC_FILE_SHEAR_ID" IS '文档共享id';
COMMENT ON COLUMN "JASDOC_FILE_SHARE_USER_REF"."SHAREDID" IS '共享对象id';
COMMENT ON COLUMN "JASDOC_FILE_SHARE_USER_REF"."SHAREDTYPE" IS '共享对象类型';

-- ----------------------------
-- Table structure for JASDOC_FOLDER
-- ----------------------------
DROP TABLE IF EXISTS "JASDOC_FOLDER";
CREATE TABLE "JASDOC_FOLDER" (
"ID" VARCHAR2(36 BYTE) NOT NULL ,
"PARENTID" VARCHAR2(36 BYTE) NOT NULL ,
"FOLDERNAME" VARCHAR2(200 BYTE) NOT NULL ,
"FOLDERTYPE" NUMBER(2) DEFAULT 1  NULL ,
"FOLDERLOCATION" VARCHAR2(500 BYTE) NULL ,
"CREATETIME" DATE NULL ,
"CREATEUSER" VARCHAR2(36 BYTE) NULL ,
"SORT" NUMBER NULL ,
"HIERARCHY" VARCHAR2(208 BYTE) NULL ,
"DELETEFLAG" VARCHAR2(36 BYTE) DEFAULT 0  NULL ,
"ISDEFAULTFAVORITE" NUMBER(1) DEFAULT 0  NULL ,
"DELETEUSER" VARCHAR2(36 BYTE) NULL ,
"UPDATEUSER" VARCHAR2(36 BYTE) NULL ,
"UPDATETIME" DATE NULL ,
"EXT_FIELD1" VARCHAR2(500 BYTE) NULL ,
"EXT_FIELD2" VARCHAR2(500 BYTE) NULL ,
"EXT_FIELD3" VARCHAR2(500 BYTE) NULL ,
"EXT_FIELD4" VARCHAR2(500 BYTE) NULL ,
"EXT_FIELD5" VARCHAR2(500 BYTE) NULL ,
"DESCRIPTION" VARCHAR2(1000 BYTE) NULL ,
"CREATEUSERNAME" NVARCHAR2(50) NULL ,
"UPDATEUSERNAME" NVARCHAR2(50) NULL 
)
LOGGING
NOCOMPRESS
NOCACHE

;
COMMENT ON TABLE "JASDOC_FOLDER" IS '1."我的收藏夹"、"文档中心"和"文档分类"中的文件夹均保存在该表中。 2.文件夹的层次编号在所有文件夹中是唯一的，包括已放入回收站的文件夹。';
COMMENT ON COLUMN "JASDOC_FOLDER"."ID" IS '节点id';
COMMENT ON COLUMN "JASDOC_FOLDER"."PARENTID" IS '父类id';
COMMENT ON COLUMN "JASDOC_FOLDER"."FOLDERNAME" IS '节点名称';
COMMENT ON COLUMN "JASDOC_FOLDER"."FOLDERTYPE" IS '1标识文档中心下的文件夹，2标识附件管理下的文件夹';
COMMENT ON COLUMN "JASDOC_FOLDER"."CREATETIME" IS '创建时间';
COMMENT ON COLUMN "JASDOC_FOLDER"."CREATEUSER" IS '添加数据用户（更改字段）';
COMMENT ON COLUMN "JASDOC_FOLDER"."DELETEFLAG" IS '该字段仅对"文档中心"里的文件夹有效。记录删除批次';
COMMENT ON COLUMN "JASDOC_FOLDER"."ISDEFAULTFAVORITE" IS '该字段仅对"我的收藏夹"里的文件夹有效。';
COMMENT ON COLUMN "JASDOC_FOLDER"."DELETEUSER" IS '删除该条数据用户id（没有删除则为空）';
COMMENT ON COLUMN "JASDOC_FOLDER"."UPDATEUSER" IS '修改数据用户（新加字段）';
COMMENT ON COLUMN "JASDOC_FOLDER"."UPDATETIME" IS '创建时间';
COMMENT ON COLUMN "JASDOC_FOLDER"."EXT_FIELD1" IS '备用字段';
COMMENT ON COLUMN "JASDOC_FOLDER"."EXT_FIELD2" IS '备用字段';
COMMENT ON COLUMN "JASDOC_FOLDER"."EXT_FIELD3" IS '备用字段';
COMMENT ON COLUMN "JASDOC_FOLDER"."EXT_FIELD4" IS '备用字段';
COMMENT ON COLUMN "JASDOC_FOLDER"."EXT_FIELD5" IS '备用字段';
COMMENT ON COLUMN "JASDOC_FOLDER"."DESCRIPTION" IS '文件夹描述';
COMMENT ON COLUMN "JASDOC_FOLDER"."CREATEUSERNAME" IS '创建者名称';
COMMENT ON COLUMN "JASDOC_FOLDER"."UPDATEUSERNAME" IS '修改者名称';

-- ----------------------------
-- Table structure for JASDOC_FOLDER_SHARE
-- ----------------------------
DROP TABLE IF EXISTS "JASDOC_FOLDER_SHARE";
CREATE TABLE "JASDOC_FOLDER_SHARE" (
"ID" VARCHAR2(36 BYTE) NOT NULL ,
"FOLDERDID" VARCHAR2(36 BYTE) NULL ,
"SHAREUSERID" VARCHAR2(36 BYTE) NULL ,
"REMARK" VARCHAR2(500 BYTE) NULL ,
"SHAREDATE" DATE NULL ,
"OVERDATE" DATE NULL ,
"SHAREPRIVILEGETYPE" NUMBER(3) NULL 
)
LOGGING
NOCOMPRESS
NOCACHE

;
COMMENT ON TABLE "JASDOC_FOLDER_SHARE" IS '文件夹共享表';
COMMENT ON COLUMN "JASDOC_FOLDER_SHARE"."FOLDERDID" IS '文件夹ID';
COMMENT ON COLUMN "JASDOC_FOLDER_SHARE"."SHAREUSERID" IS '共享人ID';
COMMENT ON COLUMN "JASDOC_FOLDER_SHARE"."REMARK" IS '共享说明';
COMMENT ON COLUMN "JASDOC_FOLDER_SHARE"."SHAREDATE" IS '共享时间';
COMMENT ON COLUMN "JASDOC_FOLDER_SHARE"."OVERDATE" IS '共享过期时间';
COMMENT ON COLUMN "JASDOC_FOLDER_SHARE"."SHAREPRIVILEGETYPE" IS '共享权限类型';

-- ----------------------------
-- Table structure for JASDOC_FOLDER_SHARE_USER_REF
-- ----------------------------
DROP TABLE IF EXISTS "JASDOC_FOLDER_SHARE_USER_REF";
CREATE TABLE "JASDOC_FOLDER_SHARE_USER_REF" (
"ID" VARCHAR2(36 BYTE) NOT NULL ,
"JASDOC_FOLDER_SHEAR_ID" VARCHAR2(36 BYTE) NULL ,
"SHAREDID" VARCHAR2(36 BYTE) NULL ,
"SHAREDTYPE" NUMBER(3) NULL 
)
LOGGING
NOCOMPRESS
NOCACHE

;
COMMENT ON TABLE "JASDOC_FOLDER_SHARE_USER_REF" IS '文件夹共享与用户关联表';
COMMENT ON COLUMN "JASDOC_FOLDER_SHARE_USER_REF"."JASDOC_FOLDER_SHEAR_ID" IS '文件夹共享ID';
COMMENT ON COLUMN "JASDOC_FOLDER_SHARE_USER_REF"."SHAREDID" IS '共享对象ID';
COMMENT ON COLUMN "JASDOC_FOLDER_SHARE_USER_REF"."SHAREDTYPE" IS '共享对象类型';

-- ----------------------------
-- Table structure for JASDOC_RECYCLEBIN
-- ----------------------------
DROP TABLE IF EXISTS "JASDOC_RECYCLEBIN";
CREATE TABLE "JASDOC_RECYCLEBIN" (
"ID" VARCHAR2(36 BYTE) NOT NULL ,
"RECYCLEOBJID" VARCHAR2(36 BYTE) NOT NULL ,
"RECYCLEOBJTYPE" NUMBER(1) DEFAULT 1  NULL ,
"RECYCLETIME" DATE NULL ,
"USERID" VARCHAR2(36 BYTE) NULL ,
"LOCATION" VARCHAR2(500 BYTE) NULL 
)
LOGGING
NOCOMPRESS
NOCACHE

;
COMMENT ON TABLE "JASDOC_RECYCLEBIN" IS '回收站信息';

-- ----------------------------
-- Table structure for JASDOC_ROLE_FOLDER_REF
-- ----------------------------
DROP TABLE IF EXISTS "JASDOC_ROLE_FOLDER_REF";
CREATE TABLE "JASDOC_ROLE_FOLDER_REF" (
"ID" VARCHAR2(40 BYTE) NOT NULL ,
"ROLEID" VARCHAR2(40 BYTE) NOT NULL ,
"FOLDERID" VARCHAR2(40 BYTE) NOT NULL ,
"FOLDERPRIVILEGETYPE" NUMBER(3) NULL 
)
LOGGING
NOCOMPRESS
NOCACHE

;
COMMENT ON TABLE "JASDOC_ROLE_FOLDER_REF" IS '角色对文件夹授权';
COMMENT ON COLUMN "JASDOC_ROLE_FOLDER_REF"."ID" IS 'uuid';
COMMENT ON COLUMN "JASDOC_ROLE_FOLDER_REF"."ROLEID" IS '对象id';
COMMENT ON COLUMN "JASDOC_ROLE_FOLDER_REF"."FOLDERID" IS '节点id';

-- ----------------------------
-- Table structure for JASDOC_USER_FOLDER_REF
-- ----------------------------
DROP TABLE IF EXISTS "JASDOC_USER_FOLDER_REF";
CREATE TABLE "JASDOC_USER_FOLDER_REF" (
"ID" VARCHAR2(40 BYTE) NOT NULL ,
"USERID" VARCHAR2(40 BYTE) NOT NULL ,
"FOLDERID" VARCHAR2(40 BYTE) NOT NULL ,
"FOLDERPRIVILEGETYPE" NUMBER(3) NULL 
)
LOGGING
NOCOMPRESS
NOCACHE

;
COMMENT ON TABLE "JASDOC_USER_FOLDER_REF" IS '用户对文件夹授权';
COMMENT ON COLUMN "JASDOC_USER_FOLDER_REF"."ID" IS 'uuid';
COMMENT ON COLUMN "JASDOC_USER_FOLDER_REF"."USERID" IS '用户id';
COMMENT ON COLUMN "JASDOC_USER_FOLDER_REF"."FOLDERID" IS '文件夹id';

-- ----------------------------
-- Indexes structure for table JASDOC_APPLY_FILE_REF
-- ----------------------------

-- ----------------------------
-- Checks structure for table JASDOC_APPLY_FILE_REF
-- ----------------------------
ALTER TABLE "JASDOC_APPLY_FILE_REF" ADD CHECK ("EVENTID" IS NOT NULL);
ALTER TABLE "JASDOC_APPLY_FILE_REF" ADD CHECK ("EVENTID" IS NOT NULL);
ALTER TABLE "JASDOC_APPLY_FILE_REF" ADD CHECK (eventid is not null);

-- ----------------------------
-- Primary Key structure for table JASDOC_APPLY_FILE_REF
-- ----------------------------
ALTER TABLE "JASDOC_APPLY_FILE_REF" ADD PRIMARY KEY ("EVENTID");

-- ----------------------------
-- Indexes structure for table JASDOC_CLASSIFY_FOLDER
-- ----------------------------

-- ----------------------------
-- Checks structure for table JASDOC_CLASSIFY_FOLDER
-- ----------------------------
ALTER TABLE "JASDOC_CLASSIFY_FOLDER" ADD CHECK ("ID" IS NOT NULL);
ALTER TABLE "JASDOC_CLASSIFY_FOLDER" ADD CHECK ("PARENTID" IS NOT NULL);
ALTER TABLE "JASDOC_CLASSIFY_FOLDER" ADD CHECK ("FOLDERNAME" IS NOT NULL);
ALTER TABLE "JASDOC_CLASSIFY_FOLDER" ADD CHECK ("ID" IS NOT NULL);
ALTER TABLE "JASDOC_CLASSIFY_FOLDER" ADD CHECK ("PARENTID" IS NOT NULL);
ALTER TABLE "JASDOC_CLASSIFY_FOLDER" ADD CHECK ("FOLDERNAME" IS NOT NULL);
ALTER TABLE "JASDOC_CLASSIFY_FOLDER" ADD CHECK (id is not null);
ALTER TABLE "JASDOC_CLASSIFY_FOLDER" ADD CHECK (parentid is not null);
ALTER TABLE "JASDOC_CLASSIFY_FOLDER" ADD CHECK (foldername is not null);

-- ----------------------------
-- Primary Key structure for table JASDOC_CLASSIFY_FOLDER
-- ----------------------------
ALTER TABLE "JASDOC_CLASSIFY_FOLDER" ADD PRIMARY KEY ("ID");

-- ----------------------------
-- Indexes structure for table JASDOC_DEPT_FOLDER_REF
-- ----------------------------

-- ----------------------------
-- Checks structure for table JASDOC_DEPT_FOLDER_REF
-- ----------------------------
ALTER TABLE "JASDOC_DEPT_FOLDER_REF" ADD CHECK ("ID" IS NOT NULL);
ALTER TABLE "JASDOC_DEPT_FOLDER_REF" ADD CHECK ("ID" IS NOT NULL);
ALTER TABLE "JASDOC_DEPT_FOLDER_REF" ADD CHECK (id is not null);

-- ----------------------------
-- Primary Key structure for table JASDOC_DEPT_FOLDER_REF
-- ----------------------------
ALTER TABLE "JASDOC_DEPT_FOLDER_REF" ADD PRIMARY KEY ("ID");

-- ----------------------------
-- Indexes structure for table JASDOC_DOWNLOAD_APPLY
-- ----------------------------

-- ----------------------------
-- Checks structure for table JASDOC_DOWNLOAD_APPLY
-- ----------------------------
ALTER TABLE "JASDOC_DOWNLOAD_APPLY" ADD CHECK ("EVENTID" IS NOT NULL);
ALTER TABLE "JASDOC_DOWNLOAD_APPLY" ADD CHECK ("EVENTID" IS NOT NULL);
ALTER TABLE "JASDOC_DOWNLOAD_APPLY" ADD CHECK (eventid is not null);

-- ----------------------------
-- Primary Key structure for table JASDOC_DOWNLOAD_APPLY
-- ----------------------------
ALTER TABLE "JASDOC_DOWNLOAD_APPLY" ADD PRIMARY KEY ("EVENTID");

-- ----------------------------
-- Indexes structure for table JASDOC_FAVORITE_FOLDER
-- ----------------------------

-- ----------------------------
-- Checks structure for table JASDOC_FAVORITE_FOLDER
-- ----------------------------
ALTER TABLE "JASDOC_FAVORITE_FOLDER" ADD CHECK ("ID" IS NOT NULL);
ALTER TABLE "JASDOC_FAVORITE_FOLDER" ADD CHECK ("PARENTID" IS NOT NULL);
ALTER TABLE "JASDOC_FAVORITE_FOLDER" ADD CHECK ("FOLDERNAME" IS NOT NULL);
ALTER TABLE "JASDOC_FAVORITE_FOLDER" ADD CHECK ("ID" IS NOT NULL);
ALTER TABLE "JASDOC_FAVORITE_FOLDER" ADD CHECK ("PARENTID" IS NOT NULL);
ALTER TABLE "JASDOC_FAVORITE_FOLDER" ADD CHECK ("FOLDERNAME" IS NOT NULL);
ALTER TABLE "JASDOC_FAVORITE_FOLDER" ADD CHECK (id is not null);
ALTER TABLE "JASDOC_FAVORITE_FOLDER" ADD CHECK (parentid is not null);
ALTER TABLE "JASDOC_FAVORITE_FOLDER" ADD CHECK (foldername is not null);

-- ----------------------------
-- Primary Key structure for table JASDOC_FAVORITE_FOLDER
-- ----------------------------
ALTER TABLE "JASDOC_FAVORITE_FOLDER" ADD PRIMARY KEY ("ID");

-- ----------------------------
-- Indexes structure for table JASDOC_FILE
-- ----------------------------

-- ----------------------------
-- Checks structure for table JASDOC_FILE
-- ----------------------------
ALTER TABLE "JASDOC_FILE" ADD CHECK ("EVENTID" IS NOT NULL);
ALTER TABLE "JASDOC_FILE" ADD CHECK ("DELETEFLAG" IS NOT NULL);
ALTER TABLE "JASDOC_FILE" ADD CHECK ("EVENTID" IS NOT NULL);
ALTER TABLE "JASDOC_FILE" ADD CHECK ("DELETEFLAG" IS NOT NULL);
ALTER TABLE "JASDOC_FILE" ADD CHECK (eventid is not null);
ALTER TABLE "JASDOC_FILE" ADD CHECK (deleteflag is not null);

-- ----------------------------
-- Primary Key structure for table JASDOC_FILE
-- ----------------------------
ALTER TABLE "JASDOC_FILE" ADD PRIMARY KEY ("EVENTID");

-- ----------------------------
-- Indexes structure for table JASDOC_FILE_ASSOCIATED
-- ----------------------------

-- ----------------------------
-- Checks structure for table JASDOC_FILE_ASSOCIATED
-- ----------------------------
ALTER TABLE "JASDOC_FILE_ASSOCIATED" ADD CHECK ("EVENTID" IS NOT NULL);
ALTER TABLE "JASDOC_FILE_ASSOCIATED" ADD CHECK ("FILEID" IS NOT NULL);
ALTER TABLE "JASDOC_FILE_ASSOCIATED" ADD CHECK ("EVENTID" IS NOT NULL);
ALTER TABLE "JASDOC_FILE_ASSOCIATED" ADD CHECK ("FILEID" IS NOT NULL);
ALTER TABLE "JASDOC_FILE_ASSOCIATED" ADD CHECK (eventid is not null);
ALTER TABLE "JASDOC_FILE_ASSOCIATED" ADD CHECK (fileid is not null);

-- ----------------------------
-- Primary Key structure for table JASDOC_FILE_ASSOCIATED
-- ----------------------------
ALTER TABLE "JASDOC_FILE_ASSOCIATED" ADD PRIMARY KEY ("EVENTID");

-- ----------------------------
-- Indexes structure for table JASDOC_FILE_BACKUP_RECOVERY
-- ----------------------------

-- ----------------------------
-- Checks structure for table JASDOC_FILE_BACKUP_RECOVERY
-- ----------------------------
ALTER TABLE "JASDOC_FILE_BACKUP_RECOVERY" ADD CHECK ("EVENTID" IS NOT NULL);
ALTER TABLE "JASDOC_FILE_BACKUP_RECOVERY" ADD CHECK ("EVENTID" IS NOT NULL);
ALTER TABLE "JASDOC_FILE_BACKUP_RECOVERY" ADD CHECK (eventid is not null);

-- ----------------------------
-- Primary Key structure for table JASDOC_FILE_BACKUP_RECOVERY
-- ----------------------------
ALTER TABLE "JASDOC_FILE_BACKUP_RECOVERY" ADD PRIMARY KEY ("EVENTID");

-- ----------------------------
-- Indexes structure for table JASDOC_FILE_CLASSIFY_REF
-- ----------------------------

-- ----------------------------
-- Checks structure for table JASDOC_FILE_CLASSIFY_REF
-- ----------------------------
ALTER TABLE "JASDOC_FILE_CLASSIFY_REF" ADD CHECK ("FILEID" IS NOT NULL);
ALTER TABLE "JASDOC_FILE_CLASSIFY_REF" ADD CHECK ("FOLDERID" IS NOT NULL);
ALTER TABLE "JASDOC_FILE_CLASSIFY_REF" ADD CHECK ("EVENTID" IS NOT NULL);
ALTER TABLE "JASDOC_FILE_CLASSIFY_REF" ADD CHECK ("FILEID" IS NOT NULL);
ALTER TABLE "JASDOC_FILE_CLASSIFY_REF" ADD CHECK ("FOLDERID" IS NOT NULL);
ALTER TABLE "JASDOC_FILE_CLASSIFY_REF" ADD CHECK ("EVENTID" IS NOT NULL);
ALTER TABLE "JASDOC_FILE_CLASSIFY_REF" ADD CHECK (folderid IS NOT NULL);
ALTER TABLE "JASDOC_FILE_CLASSIFY_REF" ADD CHECK (fileid IS NOT NULL);

-- ----------------------------
-- Primary Key structure for table JASDOC_FILE_CLASSIFY_REF
-- ----------------------------
ALTER TABLE "JASDOC_FILE_CLASSIFY_REF" ADD PRIMARY KEY ("EVENTID");

-- ----------------------------
-- Indexes structure for table JASDOC_FILE_FAVORITE_REF
-- ----------------------------

-- ----------------------------
-- Checks structure for table JASDOC_FILE_FAVORITE_REF
-- ----------------------------
ALTER TABLE "JASDOC_FILE_FAVORITE_REF" ADD CHECK ("FILEID" IS NOT NULL);
ALTER TABLE "JASDOC_FILE_FAVORITE_REF" ADD CHECK ("FOLDERID" IS NOT NULL);
ALTER TABLE "JASDOC_FILE_FAVORITE_REF" ADD CHECK ("EVENTID" IS NOT NULL);
ALTER TABLE "JASDOC_FILE_FAVORITE_REF" ADD CHECK ("FILENAME" IS NOT NULL);
ALTER TABLE "JASDOC_FILE_FAVORITE_REF" ADD CHECK ("FILEID" IS NOT NULL);
ALTER TABLE "JASDOC_FILE_FAVORITE_REF" ADD CHECK ("FOLDERID" IS NOT NULL);
ALTER TABLE "JASDOC_FILE_FAVORITE_REF" ADD CHECK ("EVENTID" IS NOT NULL);
ALTER TABLE "JASDOC_FILE_FAVORITE_REF" ADD CHECK ("FILENAME" IS NOT NULL);
ALTER TABLE "JASDOC_FILE_FAVORITE_REF" ADD CHECK (fileid is not null);
ALTER TABLE "JASDOC_FILE_FAVORITE_REF" ADD CHECK (folderid is not null);
ALTER TABLE "JASDOC_FILE_FAVORITE_REF" ADD CHECK (eventid is not null);

-- ----------------------------
-- Primary Key structure for table JASDOC_FILE_FAVORITE_REF
-- ----------------------------
ALTER TABLE "JASDOC_FILE_FAVORITE_REF" ADD PRIMARY KEY ("EVENTID");

-- ----------------------------
-- Checks structure for table JASDOC_FILE_FOLDER_REF
-- ----------------------------
ALTER TABLE "JASDOC_FILE_FOLDER_REF" ADD CHECK ("FILEID" IS NOT NULL);
ALTER TABLE "JASDOC_FILE_FOLDER_REF" ADD CHECK ("FOLDERID" IS NOT NULL);
ALTER TABLE "JASDOC_FILE_FOLDER_REF" ADD CHECK ("FILEID" IS NOT NULL);
ALTER TABLE "JASDOC_FILE_FOLDER_REF" ADD CHECK ("FOLDERID" IS NOT NULL);
ALTER TABLE "JASDOC_FILE_FOLDER_REF" ADD CHECK (fileid is not null);
ALTER TABLE "JASDOC_FILE_FOLDER_REF" ADD CHECK (folderid is not null);

-- ----------------------------
-- Indexes structure for table JASDOC_FILE_HISTORY
-- ----------------------------

-- ----------------------------
-- Checks structure for table JASDOC_FILE_HISTORY
-- ----------------------------
ALTER TABLE "JASDOC_FILE_HISTORY" ADD CHECK ("EVENTID" IS NOT NULL);
ALTER TABLE "JASDOC_FILE_HISTORY" ADD CHECK ("DELETEFLAG" IS NOT NULL);
ALTER TABLE "JASDOC_FILE_HISTORY" ADD CHECK ("VERSIONID" IS NOT NULL);
ALTER TABLE "JASDOC_FILE_HISTORY" ADD CHECK ("EVENTID" IS NOT NULL);
ALTER TABLE "JASDOC_FILE_HISTORY" ADD CHECK ("DELETEFLAG" IS NOT NULL);
ALTER TABLE "JASDOC_FILE_HISTORY" ADD CHECK ("VERSIONID" IS NOT NULL);
ALTER TABLE "JASDOC_FILE_HISTORY" ADD CHECK (eventid is not null);
ALTER TABLE "JASDOC_FILE_HISTORY" ADD CHECK (deleteflag is not null);
ALTER TABLE "JASDOC_FILE_HISTORY" ADD CHECK (versionid is not null);

-- ----------------------------
-- Primary Key structure for table JASDOC_FILE_HISTORY
-- ----------------------------
ALTER TABLE "JASDOC_FILE_HISTORY" ADD PRIMARY KEY ("EVENTID");

-- ----------------------------
-- Indexes structure for table JASDOC_FILE_SHARE
-- ----------------------------

-- ----------------------------
-- Checks structure for table JASDOC_FILE_SHARE
-- ----------------------------
ALTER TABLE "JASDOC_FILE_SHARE" ADD CHECK ("ID" IS NOT NULL);
ALTER TABLE "JASDOC_FILE_SHARE" ADD CHECK ("ID" IS NOT NULL);
ALTER TABLE "JASDOC_FILE_SHARE" ADD CHECK (id is not null);

-- ----------------------------
-- Primary Key structure for table JASDOC_FILE_SHARE
-- ----------------------------
ALTER TABLE "JASDOC_FILE_SHARE" ADD PRIMARY KEY ("ID");

-- ----------------------------
-- Indexes structure for table JASDOC_FILE_SHARE_USER_REF
-- ----------------------------

-- ----------------------------
-- Checks structure for table JASDOC_FILE_SHARE_USER_REF
-- ----------------------------
ALTER TABLE "JASDOC_FILE_SHARE_USER_REF" ADD CHECK ("ID" IS NOT NULL);
ALTER TABLE "JASDOC_FILE_SHARE_USER_REF" ADD CHECK ("ID" IS NOT NULL);
ALTER TABLE "JASDOC_FILE_SHARE_USER_REF" ADD CHECK (id is not null);

-- ----------------------------
-- Primary Key structure for table JASDOC_FILE_SHARE_USER_REF
-- ----------------------------
ALTER TABLE "JASDOC_FILE_SHARE_USER_REF" ADD PRIMARY KEY ("ID");

-- ----------------------------
-- Indexes structure for table JASDOC_FOLDER
-- ----------------------------

-- ----------------------------
-- Checks structure for table JASDOC_FOLDER
-- ----------------------------
ALTER TABLE "JASDOC_FOLDER" ADD CHECK ("ID" IS NOT NULL);
ALTER TABLE "JASDOC_FOLDER" ADD CHECK ("PARENTID" IS NOT NULL);
ALTER TABLE "JASDOC_FOLDER" ADD CHECK ("FOLDERNAME" IS NOT NULL);
ALTER TABLE "JASDOC_FOLDER" ADD CHECK ("ID" IS NOT NULL);
ALTER TABLE "JASDOC_FOLDER" ADD CHECK ("PARENTID" IS NOT NULL);
ALTER TABLE "JASDOC_FOLDER" ADD CHECK ("FOLDERNAME" IS NOT NULL);
ALTER TABLE "JASDOC_FOLDER" ADD CHECK (foldertype is null or (foldertype in (1,2,3)));
ALTER TABLE "JASDOC_FOLDER" ADD CHECK (isdefaultfavorite is null or (isdefaultfavorite in (1,0)));
ALTER TABLE "JASDOC_FOLDER" ADD CHECK (id is not null);
ALTER TABLE "JASDOC_FOLDER" ADD CHECK (parentid is not null);
ALTER TABLE "JASDOC_FOLDER" ADD CHECK (foldername is not null);

-- ----------------------------
-- Primary Key structure for table JASDOC_FOLDER
-- ----------------------------
ALTER TABLE "JASDOC_FOLDER" ADD PRIMARY KEY ("ID");

-- ----------------------------
-- Indexes structure for table JASDOC_FOLDER_SHARE
-- ----------------------------

-- ----------------------------
-- Checks structure for table JASDOC_FOLDER_SHARE
-- ----------------------------
ALTER TABLE "JASDOC_FOLDER_SHARE" ADD CHECK ("ID" IS NOT NULL);
ALTER TABLE "JASDOC_FOLDER_SHARE" ADD CHECK ("ID" IS NOT NULL);
ALTER TABLE "JASDOC_FOLDER_SHARE" ADD CHECK (id is not null);

-- ----------------------------
-- Primary Key structure for table JASDOC_FOLDER_SHARE
-- ----------------------------
ALTER TABLE "JASDOC_FOLDER_SHARE" ADD PRIMARY KEY ("ID");

-- ----------------------------
-- Indexes structure for table JASDOC_FOLDER_SHARE_USER_REF
-- ----------------------------

-- ----------------------------
-- Checks structure for table JASDOC_FOLDER_SHARE_USER_REF
-- ----------------------------
ALTER TABLE "JASDOC_FOLDER_SHARE_USER_REF" ADD CHECK ("ID" IS NOT NULL);
ALTER TABLE "JASDOC_FOLDER_SHARE_USER_REF" ADD CHECK ("ID" IS NOT NULL);
ALTER TABLE "JASDOC_FOLDER_SHARE_USER_REF" ADD CHECK (id is not null);

-- ----------------------------
-- Primary Key structure for table JASDOC_FOLDER_SHARE_USER_REF
-- ----------------------------
ALTER TABLE "JASDOC_FOLDER_SHARE_USER_REF" ADD PRIMARY KEY ("ID");

-- ----------------------------
-- Indexes structure for table JASDOC_RECYCLEBIN
-- ----------------------------

-- ----------------------------
-- Checks structure for table JASDOC_RECYCLEBIN
-- ----------------------------
ALTER TABLE "JASDOC_RECYCLEBIN" ADD CHECK ("ID" IS NOT NULL);
ALTER TABLE "JASDOC_RECYCLEBIN" ADD CHECK ("RECYCLEOBJID" IS NOT NULL);
ALTER TABLE "JASDOC_RECYCLEBIN" ADD CHECK ("ID" IS NOT NULL);
ALTER TABLE "JASDOC_RECYCLEBIN" ADD CHECK ("RECYCLEOBJID" IS NOT NULL);
ALTER TABLE "JASDOC_RECYCLEBIN" ADD CHECK (recycleobjtype is null or (recycleobjtype in (1,2,3,4)));
ALTER TABLE "JASDOC_RECYCLEBIN" ADD CHECK (id is not null);
ALTER TABLE "JASDOC_RECYCLEBIN" ADD CHECK (recycleobjid is not null);

-- ----------------------------
-- Primary Key structure for table JASDOC_RECYCLEBIN
-- ----------------------------
ALTER TABLE "JASDOC_RECYCLEBIN" ADD PRIMARY KEY ("ID");

-- ----------------------------
-- Indexes structure for table JASDOC_ROLE_FOLDER_REF
-- ----------------------------

-- ----------------------------
-- Checks structure for table JASDOC_ROLE_FOLDER_REF
-- ----------------------------
ALTER TABLE "JASDOC_ROLE_FOLDER_REF" ADD CHECK ("ID" IS NOT NULL);
ALTER TABLE "JASDOC_ROLE_FOLDER_REF" ADD CHECK ("ROLEID" IS NOT NULL);
ALTER TABLE "JASDOC_ROLE_FOLDER_REF" ADD CHECK ("FOLDERID" IS NOT NULL);
ALTER TABLE "JASDOC_ROLE_FOLDER_REF" ADD CHECK ("ID" IS NOT NULL);
ALTER TABLE "JASDOC_ROLE_FOLDER_REF" ADD CHECK ("ROLEID" IS NOT NULL);
ALTER TABLE "JASDOC_ROLE_FOLDER_REF" ADD CHECK ("FOLDERID" IS NOT NULL);
ALTER TABLE "JASDOC_ROLE_FOLDER_REF" ADD CHECK (id is not null);
ALTER TABLE "JASDOC_ROLE_FOLDER_REF" ADD CHECK (roleid is not null);
ALTER TABLE "JASDOC_ROLE_FOLDER_REF" ADD CHECK (folderid is not null);

-- ----------------------------
-- Primary Key structure for table JASDOC_ROLE_FOLDER_REF
-- ----------------------------
ALTER TABLE "JASDOC_ROLE_FOLDER_REF" ADD PRIMARY KEY ("ID");

-- ----------------------------
-- Indexes structure for table JASDOC_USER_FOLDER_REF
-- ----------------------------

-- ----------------------------
-- Checks structure for table JASDOC_USER_FOLDER_REF
-- ----------------------------
ALTER TABLE "JASDOC_USER_FOLDER_REF" ADD CHECK ("ID" IS NOT NULL);
ALTER TABLE "JASDOC_USER_FOLDER_REF" ADD CHECK ("USERID" IS NOT NULL);
ALTER TABLE "JASDOC_USER_FOLDER_REF" ADD CHECK ("FOLDERID" IS NOT NULL);
ALTER TABLE "JASDOC_USER_FOLDER_REF" ADD CHECK ("ID" IS NOT NULL);
ALTER TABLE "JASDOC_USER_FOLDER_REF" ADD CHECK ("USERID" IS NOT NULL);
ALTER TABLE "JASDOC_USER_FOLDER_REF" ADD CHECK ("FOLDERID" IS NOT NULL);
ALTER TABLE "JASDOC_USER_FOLDER_REF" ADD CHECK (userid is not null);
ALTER TABLE "JASDOC_USER_FOLDER_REF" ADD CHECK (folderid is not null);

-- ----------------------------
-- Primary Key structure for table JASDOC_USER_FOLDER_REF
-- ----------------------------
ALTER TABLE "JASDOC_USER_FOLDER_REF" ADD PRIMARY KEY ("ID");

-- ----------------------------
-- Foreign Key structure for table "JASDOC_FILE_ASSOCIATED"
-- ----------------------------
ALTER TABLE "JASDOC_FILE_ASSOCIATED" ADD FOREIGN KEY ("FILEID") REFERENCES "JASDOC_FILE" ("EVENTID");

INSERT INTO "JASDOC_FOLDER" ("ID", "PARENTID", "FOLDERNAME", "FOLDERTYPE", "FOLDERLOCATION", "CREATETIME", "CREATEUSER", "SORT", "HIERARCHY", "DELETEFLAG", "ISDEFAULTFAVORITE", "DELETEUSER", "UPDATEUSER", "UPDATETIME", "EXT_FIELD1", "EXT_FIELD2", "EXT_FIELD3", "EXT_FIELD4", "EXT_FIELD5", "DESCRIPTION", "CREATEUSERNAME", "UPDATEUSERNAME", "ROWID") VALUES ('8b0d4463-af4e-4e83-8004-659833162ee9', '190c533a-2753-4588-99f2-28a8f897721f', '建（构）筑物', '2', '\attachment\建（构）筑物', TO_DATE('2018-04-11 16:57:06', 'SYYYY-MM-DD HH24:MI:SS'), '1df621c3346c4a8bac91d1238afc8400', '1', '800011530001', '0', NULL, NULL, '1df621c3346c4a8bac91d1238afc8400', TO_DATE('2018-04-11 16:57:06', 'SYYYY-MM-DD HH24:MI:SS'), NULL, NULL, NULL, NULL, NULL, '关联文档存放目录', NULL, NULL, 'AAAmB9AAUAAABVsAAA');
INSERT INTO "JASDOC_FOLDER" ("ID", "PARENTID", "FOLDERNAME", "FOLDERTYPE", "FOLDERLOCATION", "CREATETIME", "CREATEUSER", "SORT", "HIERARCHY", "DELETEFLAG", "ISDEFAULTFAVORITE", "DELETEUSER", "UPDATEUSER", "UPDATETIME", "EXT_FIELD1", "EXT_FIELD2", "EXT_FIELD3", "EXT_FIELD4", "EXT_FIELD5", "DESCRIPTION", "CREATEUSERNAME", "UPDATEUSERNAME", "ROWID") VALUES ('ca60e123-d25e-4e93-8274-7be9912048ec', '0', '文档中心', '1', '\文档中心', TO_DATE('2012-11-30 00:00:00', 'SYYYY-MM-DD HH24:MI:SS'), '1df621c3346c4a8bac91d1238afc8400', '1', '80001151', '0', '0', NULL, '1df621c3346c4a8bac91d1238afc8400', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'AAAmB9AAUAAABVuAAA');
INSERT INTO "JASDOC_FOLDER" ("ID", "PARENTID", "FOLDERNAME", "FOLDERTYPE", "FOLDERLOCATION", "CREATETIME", "CREATEUSER", "SORT", "HIERARCHY", "DELETEFLAG", "ISDEFAULTFAVORITE", "DELETEUSER", "UPDATEUSER", "UPDATETIME", "EXT_FIELD1", "EXT_FIELD2", "EXT_FIELD3", "EXT_FIELD4", "EXT_FIELD5", "DESCRIPTION", "CREATEUSERNAME", "UPDATEUSERNAME", "ROWID") VALUES ('190c533a-2753-4588-99f2-28a8f897721f', '0', 'attachment', '2', '\attachment', TO_DATE('2018-04-11 16:57:06', 'SYYYY-MM-DD HH24:MI:SS'), '1df621c3346c4a8bac91d1238afc8400', '1', '80001153', '0', NULL, NULL, '1df621c3346c4a8bac91d1238afc8400', TO_DATE('2018-04-11 16:57:06', 'SYYYY-MM-DD HH24:MI:SS'), NULL, NULL, NULL, NULL, NULL, '关联文档存放目录', NULL, NULL, 'AAAmB9AAUAAABVuAAB');
