/*
*	登陆日志表
*/

-- ----------------------------
-- Table structure for SYS_LOGIN_LOG
-- ----------------------------
CREATE TABLE "SYS_LOGIN_LOG" (
"OID" NVARCHAR2(36) NOT NULL ,
"USER_ID" NVARCHAR2(36) NOT NULL ,
"USER_NAME" NVARCHAR2(50) NOT NULL ,
"LOGIN_NAME" NVARCHAR2(50) NOT NULL ,
"UNIT_ID" NVARCHAR2(36) NOT NULL ,
"UNIT_NAME" NVARCHAR2(50) NOT NULL ,
"UNIT_NAME_FULLPATH" NVARCHAR2(200) NULL ,
"TOKEN" NVARCHAR2(100) NOT NULL ,
"APP_ID" NVARCHAR2(36) NULL ,
"APP_NAME" NVARCHAR2(50) NULL ,
"LOGIN_DATETIME" TIMESTAMP(6)  NOT NULL ,
"EXIT_DATETIME" TIMESTAMP(6)  NULL ,
"SERVER_IP" NVARCHAR2(25) NULL ,
"CLIENT_IP" NVARCHAR2(25) NULL ,
"OS_TYPE" NVARCHAR2(20) NULL ,
"BROWSER_TYPE" NVARCHAR2(20) NULL ,
"BROWSER_VER" NVARCHAR2(20) NULL ,
"SCREEN_DPI" NVARCHAR2(20) NULL 
)
LOGGING
NOCOMPRESS
NOCACHE

;

-- ----------------------------
-- Indexes structure for table SYS_LOGIN_LOG
-- ----------------------------
CREATE INDEX "I1216OID"
ON "SYS_LOGIN_LOG" ("OID" ASC)
NOLOGGING
VISIBLE;

-- ----------------------------
-- Checks structure for table SYS_LOGIN_LOG
-- ----------------------------
ALTER TABLE "SYS_LOGIN_LOG" ADD CHECK ("OID" IS NOT NULL);
ALTER TABLE "SYS_LOGIN_LOG" ADD CHECK ("USER_ID" IS NOT NULL);
ALTER TABLE "SYS_LOGIN_LOG" ADD CHECK ("USER_NAME" IS NOT NULL);
ALTER TABLE "SYS_LOGIN_LOG" ADD CHECK ("LOGIN_NAME" IS NOT NULL);
ALTER TABLE "SYS_LOGIN_LOG" ADD CHECK ("UNIT_ID" IS NOT NULL);
ALTER TABLE "SYS_LOGIN_LOG" ADD CHECK ("UNIT_NAME" IS NOT NULL);
ALTER TABLE "SYS_LOGIN_LOG" ADD CHECK ("TOKEN" IS NOT NULL);
ALTER TABLE "SYS_LOGIN_LOG" ADD CHECK ("LOGIN_DATETIME" IS NOT NULL);
ALTER TABLE "SYS_LOGIN_LOG" ADD CHECK ("OID" IS NOT NULL);
ALTER TABLE "SYS_LOGIN_LOG" ADD CHECK ("USER_ID" IS NOT NULL);
ALTER TABLE "SYS_LOGIN_LOG" ADD CHECK ("USER_NAME" IS NOT NULL);
ALTER TABLE "SYS_LOGIN_LOG" ADD CHECK ("LOGIN_NAME" IS NOT NULL);
ALTER TABLE "SYS_LOGIN_LOG" ADD CHECK ("UNIT_ID" IS NOT NULL);
ALTER TABLE "SYS_LOGIN_LOG" ADD CHECK ("UNIT_NAME" IS NOT NULL);
ALTER TABLE "SYS_LOGIN_LOG" ADD CHECK ("TOKEN" IS NOT NULL);
ALTER TABLE "SYS_LOGIN_LOG" ADD CHECK ("LOGIN_DATETIME" IS NOT NULL);
